// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXUsunp94itluRznaAYeHQoT43j4VNRdg',
    appId: '1:122496376373:web:935feaf676eb5ea8abdb7c',
    messagingSenderId: '122496376373',
    projectId: 'chatnest-878f7',
    authDomain: 'chatnest-878f7.firebaseapp.com',
    storageBucket: 'chatnest-878f7.appspot.com',
    measurementId: 'G-9709WTL6PS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfdMoTT4ce9FXZIWZw13gjavncBoH0j58',
    appId: '1:122496376373:android:47f9b4ad5ea20597abdb7c',
    messagingSenderId: '122496376373',
    projectId: 'chatnest-878f7',
    storageBucket: 'chatnest-878f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTGeVodgVtrS1dN2PQ3olofxT47hLLaSg',
    appId: '1:122496376373:ios:7c3bcdca4e57dd31abdb7c',
    messagingSenderId: '122496376373',
    projectId: 'chatnest-878f7',
    storageBucket: 'chatnest-878f7.appspot.com',
    iosBundleId: 'com.example.chatNest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTGeVodgVtrS1dN2PQ3olofxT47hLLaSg',
    appId: '1:122496376373:ios:117d978d5165122babdb7c',
    messagingSenderId: '122496376373',
    projectId: 'chatnest-878f7',
    storageBucket: 'chatnest-878f7.appspot.com',
    iosBundleId: 'com.example.chatNest.RunnerTests',
  );
}
